### ISSUE TITLE
Calling dispatch_async twice results in the first closure's variables being replaced, if it hasn't been run yet

### ISSUE THREAD

**Issue by michaeleiselsc** [SSheldon/rust-dispatch#8]
I guess they use shared state?

**Comment by SSheldon** [comment]
Hey @michaeleiselsc, this sounds pretty bad 😮 Could you share some code that demonstrates this issue?

**Comment by michaeleiselsc** [comment]
Ah, I see what happened. It's because i'm using an FnOnce, and since the memory is statically allocated, it gets changed each time. Perhaps the API should only accept FnMut?

**Comment by michaeleiselsc** [comment]
Nope, I was wrong. It's because I had the following code:
```
let string = unsafe { CStr::from_ptr(c_str) }.to_bytes().clone();
QUEUE.async(move || {
    do_stuff(string);
});
```
because it's unsafe, rust can't infer the lifetime of `string` until it sees that the FnOnce is 'static, and so it lets `string` be a `&'static [u8]`

**Comment by SSheldon** [comment]
Oh yikes, well glad you found your issue 😊 Sounds like no issue in `dispatch` then, so I'll close this out.
